name: Deploy React to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      # Critical: don't use `npm ci` here (it will strictly follow a possibly
      # broken lock from another OS). Use `npm install`.
      - name: Install deps
        run: npm install --no-audit --no-fund

      # Workaround: explicitly install Rollup's Linux x64 binary so
      # require('@rollup/rollup-linux-x64-gnu') always resolves on the runner.
      # Pin to v4 to match modern Vite/Rollup.
      - name: Workaround npm optional-deps bug (force Rollup Linux binary)
        run: npm i -D @rollup/rollup-linux-x64-gnu@^4

      - name: Build
        run: npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
